### ISSUE TITLE
Makefile Feedback

### ISSUE THREAD

**Issue by LisaSeq** [UBC-MDS/Car-Acceptability-Prediction#16]
Please review and/or test the Makefile. Found in the repo here on the make_file branch: https://github.com/UBC-MDS/Car-Acceptability-Prediction/blob/make_file/Makefile

**Comment by louiewang820** [comment]
I tested `make clean` and all worked. 'make all' returns an error saying '*** No rule to make target `data/processed/training.csv', needed by `result/eda_plot1_corr.png'.  Stop.' This is because we use the "traing csv" as `train.csv` instead of `training.csv` in `reprocessing of the data and data splitting into train and test` stage

**Comment by LisaSeq** [comment]
Fixed this in the latest commit: https://github.com/UBC-MDS/Car-Acceptability-Prediction/commit/2be01a83fda8bba7d236d3191b7cedc97b509900
