### ISSUE TITLE
Milestone 1 - Team Contract Review

### ISSUE THREAD

**Issue by LisaSeq** [UBC-MDS/Car-Acceptability-Prediction#3]
Please review the draft and add any feedback. Some questions are left in red for comments.

**Comment by pengzh313** [comment]
Lisa: The draft of Team Contract has covered most of what we want. I only have a few suggestions as below for you and other team mates to consider:

Under the "**Communication Plan**":
(1) Should we use GitHub Issues as the main channel during the whole project. Slack could be a supplement to GitHub Issues in case we send out a group reminder or need a prompt response from team members, etc.

(2) For the daily check in with the team lead, I am thinking if we could also create a particular GitHub Issue for each week to include the weekly task assignments, timelines, and let team members to write their daily progress there. The advantage is to utilize this formal project communication channel and facilitate the transparency (the progress will be seen by all members) but the downside is it seems not well-organized since each individual writes comments everyday so the Issue could become messy at the end. Lisa had listed a few tools (like Kanban Board or Trello). I wonder if these tools could be more effective? If we do not have time to research on these tools before the deadline of Milestone 1, we can leave it for now and update the communication plan later on. 

(3) Should we add a particular term to highlight we value the work-life balance (or the family first culture):
No project-related communication will occur from 6:00 pm on Saturday to 6:00 pm on Sunday.

**Comment by LisaSeq** [comment]
Thanks for the thorough review. I have made the updates. We can try using Github issues for now to handle our daily tasks and progress and see how it works for us.
